spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taiger?useUnicode=true&characterEncoding=utf8
    username: taiger	
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: create
    generate-ddl: false
    show-sql: true
server:
  port: 8016